// shared/Data.ts

export interface BaseModel {
  id: number;
  name: string;
  lat?: number;
  lng?: number;
  rating?: number;
  distance?: number; // in kilometers
  estimatedTime?: number; // in minutes
  icon?: string; // optional for instances
  value?: string; // optional for categories
  categoryId?: number; // optional for instances
}

export interface Instance extends BaseModel {
  lat: number;
  lng: number;
}

export interface Category extends BaseModel {
  value: string;
  icon: string;
  instances?: Instance[];
}

// Full mock data
export const CategoryListData: Category[] = [
  {
    id: 0,
    name: "Drivers",
    value: "drivers",
    icon: "/driver.png",

    instances: [
      {
        id: 0,
        categoryId: 0,
        name: "John Doe",
        lat: 53.7129,
        lng: -44.005,
        rating: 4.8,
        distance: 2.1,
        estimatedTime: 7,
      },
      {
        id: 1,
        categoryId: 0,
        name: "Jane Smith",
        lat: 33.713,
        lng: -74.007,
        rating: 4.6,
        distance: 2.6,
        estimatedTime: 9,
      },
      {
        id: 2,
        categoryId: 0,
        name: "Alex Johnson",
        lat: 53.7127,
        lng: -69.004,
        rating: 4.7,
        distance: 2.4,
        estimatedTime: 8,
      },
    ],
  },
  {
    id: 1,
    name: "Jobs",
    value: "jobs",
    icon: "/job.png",

    instances: [
      {
        id: 3,
        categoryId: 1,
        name: "Delivery",
        lat: 20.714,
        lng: -54.006,
        rating: 4.0,
        distance: 5,
        estimatedTime: 14,
      },
      {
        id: 4,
        categoryId: 1,
        name: "Cleaning",
        lat: 20.7135,
        lng: -34.008,
        rating: 4.3,
        distance: 5.2,
        estimatedTime: 16,
      },
      {
        id: 5,
        categoryId: 1,
        name: "Software Developer",
        lat: 20.7139,
        lng: -64.009,
        rating: 4.5,
        distance: 5.1,
        estimatedTime: 15,
      },
    ],
  },
  {
    id: 2,
    name: "Services",
    value: "services",
    icon: "/service.png",

    instances: [
      {
        id: 6,
        categoryId: 2,
        name: "Plumbing",
        lat: 70.715,
        lng: -44.007,
        rating: 4.4,
        distance: 1.9,
        estimatedTime: 7,
      },
      {
        id: 7,
        categoryId: 2,
        name: "Electrician",
        lat: 70.7145,
        lng: -44.0085,
        rating: 4.5,
        distance: 1.7,
        estimatedTime: 6,
      },
      {
        id: 8,
        categoryId: 2,
        name: "Mechanic",
        lat: 70.7147,
        lng: -44.009,
        rating: 4.6,
        distance: 1.8,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 3,
    name: "Hotels",
    value: "hotels",
    icon: "/hotel.jpg",

    instances: [
      {
        id: 9,
        categoryId: 3,
        name: "Hilton",
        lat: 40.716,
        lng: -44.008,
        rating: 4.7,
        distance: 7.0,
        estimatedTime: 19,
      },
      {
        id: 10,
        categoryId: 3,
        name: "Marriott",
        lat: 50.7155,
        lng: -54.0095,
        rating: 4.6,
        distance: 7.3,
        estimatedTime: 21,
      },
      {
        id: 11,
        categoryId: 3,
        name: "Holiday Inn",
        lat: 33.7158,
        lng: -66.01,
        rating: 4.5,
        distance: 7.2,
        estimatedTime: 20,
      },
    ],
  },
  {
    id: 4,
    name: "Events",
    value: "events",
    icon: "/event.jpeg",

    instances: [
      {
        id: 12,
        categoryId: 4,
        name: "Concert",
        lat: 70.717,
        lng: -43.009,
        rating: 4.4,
        distance: 3.2,
        estimatedTime: 9,
      },
      {
        id: 13,
        categoryId: 4,
        name: "Exhibition",
        lat: 40.7165,
        lng: -63.011,
        rating: 4.3,
        distance: 3.4,
        estimatedTime: 11,
      },
      {
        id: 14,
        categoryId: 4,
        name: "Conference",
        lat: 77.7168,
        lng: -73.012,
        rating: 4.2,
        distance: 3.3,
        estimatedTime: 10,
      },
    ],
  },
  {
    id: 5,
    name: "Places",
    value: "places",
    icon: "/place.png",

    instances: [
      {
        id: 15,
        categoryId: 5,
        name: "Central Park",
        lat: 77.718,
        lng: -33.01,
        rating: 4.9,
        distance: 0.8,
        estimatedTime: 2,
      },
      {
        id: 16,
        categoryId: 5,
        name: "Statue of Liberty",
        lat: 55.7175,
        lng: -13.012,
        rating: 4.8,
        distance: 0.9,
        estimatedTime: 3,
      },
      {
        id: 17,
        categoryId: 5,
        name: "Times Square",
        lat: 36.7178,
        lng: -73.013,
        rating: 4.7,
        distance: 1,
        estimatedTime: 4,
      },
    ],
  },
  {
    id: 6,
    name: "Car Rentals",
    value: "car_rentals",
    icon: "/carrental.png",

    instances: [
      {
        id: 18,
        categoryId: 6,
        name: "Hertz",
        lat: 69.719,
        lng: -66.011,
        rating: 4.3,
        distance: 12.5,
        estimatedTime: 24,
      },
      {
        id: 19,
        categoryId: 6,
        name: "Avis",
        lat: 49.7185,
        lng: -66.013,
        rating: 4.4,
        distance: 12.6,
        estimatedTime: 25,
      },
      {
        id: 20,
        categoryId: 6,
        name: "Enterprise",
        lat: 39.7188,
        lng: -66.014,
        rating: 4.5,
        distance: 12.7,
        estimatedTime: 26,
      },
    ],
  },
  // continuation of CategoryListData
  {
    id: 7,
    name: "Gas station",
    value: "gas_station",
    icon: "/gas.png",

    instances: [
      {
        id: 21,
        categoryId: 7,
        name: "Fuel Express",
        lat: 60.72,
        lng: -74.012,
        rating: 4.0,
        distance: 4.6,
        estimatedTime: 11,
      },
      {
        id: 22,
        categoryId: 7,
        name: "QuickFuel",
        lat: 55.7195,
        lng: -74.014,
        rating: 4.2,
        distance: 4.8,
        estimatedTime: 13,
      },
      {
        id: 23,
        categoryId: 7,
        name: "Shell",
        lat: 44.7198,
        lng: -74.015,
        rating: 4.1,
        distance: 4.7,
        estimatedTime: 12,
      },
    ],
  },
  {
    id: 8,
    name: "Restaurant",
    value: "restaurant",
    icon: "/rest.png",

    instances: [
      {
        id: 24,
        categoryId: 8,
        name: "Pizza Place",
        lat: 40.721,
        lng: -74.013,
        rating: 4.6,
        distance: 2.1,
        estimatedTime: 6,
      },
      {
        id: 25,
        categoryId: 8,
        name: "Sushi Bar",
        lat: 40.7205,
        lng: -74.015,
        rating: 4.7,
        distance: 1.9,
        estimatedTime: 5,
      },
      {
        id: 26,
        categoryId: 8,
        name: "Steakhouse",
        lat: 40.7208,
        lng: -74.016,
        rating: 4.5,
        distance: 2.0,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 9,
    name: "Supermarket",
    value: "supermarket",
    icon: "/supermarket.jpeg",

    instances: [
      {
        id: 27,
        categoryId: 9,
        name: "Fresh Mart",
        lat: 50.722,
        lng: -44.014,
        rating: 4.5,
        distance: 1.4,
        estimatedTime: 5,
      },
      {
        id: 28,
        categoryId: 9,
        name: "Whole Foods",
        lat: 90.7215,
        lng: -44.016,
        rating: 4.6,
        distance: 1.6,
        estimatedTime: 6,
      },
      {
        id: 29,
        categoryId: 9,
        name: "Trader Joe’s",
        lat: 55.7218,
        lng: -44.017,
        rating: 4.4,
        distance: 1.5,
        estimatedTime: 5,
      },
    ],
  },
  {
    id: 10,
    name: "Pharmacy",
    value: "pharmacy",
    icon: "/pharmacy.jpeg",

    instances: [
      {
        id: 30,
        categoryId: 10,
        name: "HealthCare Pharmacy",
        lat: 70.723,
        lng: -24.015,
        rating: 4.2,
        distance: 2.6,
        estimatedTime: 8,
      },
      {
        id: 31,
        categoryId: 10,
        name: "CVS",
        lat: 70.7225,
        lng: -24.017,
        rating: 4.3,
        distance: 2.8,
        estimatedTime: 10,
      },
      {
        id: 32,
        categoryId: 10,
        name: "Walgreens",
        lat: 70.7228,
        lng: -24.018,
        rating: 4.4,
        distance: 2.7,
        estimatedTime: 9,
      },
    ],
  },
  {
    id: 11,
    name: "Cafe",
    value: "cafe",
    icon: "/cafee.jpeg",

    instances: [
      {
        id: 33,
        categoryId: 11,
        name: "Coffee Corner",
        lat: 10.724,
        lng: -74.016,
        rating: 4.7,
        distance: 1.1,
        estimatedTime: 3,
      },
      {
        id: 34,
        categoryId: 11,
        name: "Starbucks",
        lat: 10.7235,
        lng: -74.018,
        rating: 4.8,
        distance: 1.3,
        estimatedTime: 4,
      },
      {
        id: 35,
        categoryId: 11,
        name: "Blue Bottle",
        lat: 10.7238,
        lng: -74.019,
        rating: 4.6,
        distance: 1.2,
        estimatedTime: 4,
      },
    ],
  },
  {
    id: 12,
    name: "Bookstore",
    value: "bookstore",
    icon: "/bookstore.jpeg",

    instances: [
      {
        id: 36,
        categoryId: 12,
        name: "The Reading Room",
        lat: 40.725,
        lng: -34.017,
        rating: 4.6,
        distance: 2.9,
        estimatedTime: 10,
      },
      {
        id: 37,
        categoryId: 12,
        name: "Barnes & Noble",
        lat: 40.7245,
        lng: -34.019,
        rating: 4.7,
        distance: 3.1,
        estimatedTime: 12,
      },
      {
        id: 38,
        categoryId: 12,
        name: "Indie Books",
        lat: 40.7248,
        lng: -34.02,
        rating: 4.5,
        distance: 3.0,
        estimatedTime: 11,
      },
    ],
  },
  {
    id: 13,
    name: "Gym",
    value: "gym",
    icon: "/gym.png",

    instances: [
      {
        id: 39,
        categoryId: 13,
        name: "Iron Paradise",
        lat: 70.726,
        lng: -34.018,
        rating: 4.4,
        distance: 6.0,
        estimatedTime: 17,
      },
      {
        id: 40,
        categoryId: 13,
        name: "Gold’s Gym",
        lat: 70.7255,
        lng: -34.02,
        rating: 4.5,
        distance: 6.2,
        estimatedTime: 18,
      },
      {
        id: 41,
        categoryId: 13,
        name: "Planet Fitness",
        lat: 60.7258,
        lng: -34.021,
        rating: 4.3,
        distance: 6.1,
        estimatedTime: 18,
      },
    ],
  },
  {
    id: 14,
    name: "Flower Shop",
    value: "flower_shop",
    icon: "/flowers.jpeg",

    instances: [
      {
        id: 42,
        categoryId: 14,
        name: "Bloom & Co.",
        lat: 60.727,
        lng: -54.019,
        rating: 4.2,
        distance: 1.8,
        estimatedTime: 6,
      },
      {
        id: 43,
        categoryId: 14,
        name: "Rose Boutique",
        lat: 60.7265,
        lng: -54.021,
        rating: 4.3,
        distance: 2.0,
        estimatedTime: 8,
      },
      {
        id: 44,
        categoryId: 14,
        name: "Petal House",
        lat: 60.7268,
        lng: -54.022,
        rating: 4.1,
        distance: 1.9,
        estimatedTime: 7,
      },
    ],
  },
];
